// const data = [1,2,3]
// data.push(4)
// console.log(data)
// console.log(data.pop())

const data = [
    'Concentration',
'Conceal/Reveal Object',
'Lip Reading',
'Perception',
'Tracking',
'Athletics',
'Contortionist',
'Dance',
'Endurance',
'Resist Torture/Drugs',
'Stealth',
'Drive Land Vehicle',
'Pilot Air Vehicle',
'Pilot Sea Vehicle',
'Riding',
'Accounting',
'Animal Handling',
'Bureaucracy',
'Business',
'Composition',
'Criminology',
'Cryptography',
'Deduction',
'Education',
'Gamble',
'Brawling',
'Evasion',
'Martial Arts',
'Melee Weapon',
'Archery',
'Autofire',
'Handgun',
'Library Search',
'Tactics',
'Wilderness Survival',
'Acting',
'Heavy Weapons',
'Shoulder Arms',
'Bribery',
'Conversation',
'Human Perception',
'Interrogation',
'Persuasion',
'Personal Grooming',
'Streetwise',
'Trading',
'Wardrobe & Style',
'Air Vehicle Tech',
'Basic Tech',
'Cybertech',
'Demolitions',
'Electronics/Security Tech',
'First Aid',
'Forgery',
'Land Vehicle Tech',
'Paint/Draw/Sculpt',
'Paramedic',
'Photography/Film',
'Pick Lock',
'Pick Pocket',
'Sea Vehicle Tech',
'Weaponstech',
'Language: English',
'Language: Streetslang',
'Local Expert: Home',
]

data.sort();

console.log(JSON.stringify(data));

// data = ["Accounting","Acting","Air Vehicle Tech","Animal Handling","Archery","Athletics","Autofire","Basic Tech","Brawling","Bribery","Bureaucracy","Business","Composition","Conceal/Reveal Object","Concentration","Contortionist","Conversation","Criminology","Cryptography","Cybertech","Dance","Deduction","Demolitions","Drive Land Vehicle","Education","Electronics/Security Tech","Endurance","Evasion","First Aid","Forgery","Gamble","Handgun","Heavy Weapons","Human Perception","Interrogation","Land Vehicle Tech","Language: English","Language: Streetslang","Library Search","Lip Reading","Local Expert: Home","Martial Arts","Melee Weapon","Paint/Draw/Sculpt","Paramedic","Perception","Personal Grooming","Persuasion","Photography/Film","Pick Lock","Pick Pocket","Pilot Air Vehicle","Pilot Sea Vehicle","Resist Torture/Drugs","Riding","Sea Vehicle Tech","Shoulder Arms","Stealth","Streetwise","Tactics","Tracking","Trading","Wardrobe & Style","Weaponstech","Wilderness Survival"]
console.log(data.length);